Fixed Unable to connect to the remote server
Overview of the Scenario:
We have a  storefront and an admin in Windows Azure that are configured in two locations. 
When we send more than 10-15 request per seconds to admin, we got Unable to connect to the remote server error or slow response, but the admin works as expected. 

Solution:
We could fix it if set HttpClientHandler lifetime to PerRequestLifetimeManager.

Error Details:
System.Net.WebException: Unable to connect to the remote server
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
...